Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,14 +26,14 @@ jobs:
       - name: Running Xcode version Is?
         run: /usr/bin/xcodebuild -version
 
-      - name: Build Cleanup
-        run: |
-          xcodebuild clean -project WfmUser.xcodeproj -scheme WfmUser | xcpretty
+     # - name: Build Cleanup
+     #   run: |
+     #     xcodebuild clean -project WfmUser.xcodeproj -scheme WfmUser | xcpretty
 
             
-      - name: Build Test
-        run: |
-          xcodebuild test -project WfmUser.xcodeproj -scheme WfmUser -destination 'platform=iOS   Simulator,name=iPhone 16,OS=18.2' | xcpretty -s
+     # - name: Build Test
+     #   run: |
+     #     xcodebuild test -project WfmUser.xcodeproj -scheme WfmUser -destination 'platform=iOS   Simulator,name=iPhone 16,OS=18.2' | xcpretty -s
 
       - name: Remove existing keychain if exists
         run: |
@@ -57,23 +57,31 @@ jobs:
           team-id: ${{ secrets.TEAM_ID }}
           certificate-password: ${{ secrets.P12_PASSWORD }}
 
-     # - name: Install Fastlane
-     #   run: sudo gem install fastlane
+      - name: Print .ipa path from yukiarrr action
+        run: echo "IPA_PATH = ${{ steps.build_ipa.outputs.ipa_path }}"
 
-      - name: Upload App with Fastlane (API Key)
-        if: success()
-        env:
-          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
-          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
-          APP_STORE_CONNECT_API_KEY_P8_BASE64: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
+      - name: Find .ipa manually if output is empty
+        id: manual_ipa
         run: |
           IPA_PATH="${{ steps.build_ipa.outputs.ipa_path }}"
           if [ -z "$IPA_PATH" ]; then
-            echo "Error: IPA path from build step is empty."
+            echo "Trying to find .ipa manually..."
+            IPA_PATH=$(find . -type f -name "*.ipa" | head -n 1)
+          fi
+
+          if [ -z "$IPA_PATH" ]; then
+            echo "IPA not found!"
             exit 1
           fi
-          echo "Uploading $IPA_PATH using Fastlane..."
-          bundle exec fastlane release ipa_path:"$IPA_PATH"
+
+          echo "Found IPA at: $IPA_PATH"
+          echo "ipa_path=$IPA_PATH" >> $GITHUB_OUTPUT
+
+      - name: Upload .ipa to GitHub Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+         name: ios-app
+         path: ${{ steps.manual_ipa.outputs.ipa_path }}
 
      # - name: Find IPA file and export path
      #   id: find_ipa
@@ -86,6 +94,21 @@ jobs:
      #     echo "IPA_PATH=$IPA_PATH" >> $GITHUB_ENV
      #     echo "ipa_path=$IPA_PATH" >> $GITHUB_OUTPUT
      #     ls -l "$IPA_PATH"
+
+      - name: Upload App with Fastlane (API Key)
+        if: success()
+        env:
+          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
+          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
+          APP_STORE_CONNECT_API_KEY_P8_BASE64: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
+        run: |
+          IPA_PATH="${{ steps.manual_ipa.outputs.ipa_path }}"
+          if [ -z "$IPA_PATH" ]; then
+            echo "Error: IPA path from build step is empty."
+            exit 1
+          fi
+          echo "Uploading $IPA_PATH using Fastlane..."
+          bundle exec fastlane release ipa_path:"$IPA_PATH"
 
      # - name: Decode App Store Connect API Key
      #   run: |
